#!/bin/bash
#
# Manual regression tests for the dfps config hot-reload keepalive fix.
#
# Background:
#   Previously the daemon killed the running instance BEFORE starting the new
#   one on a config file update. A broken config (missing '*'/ '-' rules,
#   malformed rules, invalid refresh rate values) made the new instance exit
#   during DynamicFps::LoadConfig, taking the whole service down.
#   The fix (source/main.cpp, ReloadApp) starts the candidate instance first,
#   health-checks it, and only then retires the old instance. A bad config
#   must never stop the running service.
#
# Prerequisites:
#   1. Built binary: ./build.sh Debug make   (or: ./build.sh Release make)
#   2. A rooted Android device connected via adb (Magisk su)
#
# Usage:
#   ./test.sh list          # list all test units
#   ./test.sh push          # push binary + device-side script to the device
#   ./test.sh all           # run every unit sequentially
#   ./test.sh <unit> ...    # run one or more units manually, e.g.:
#   ./test.sh t02_missing_universal_rule_keeps_alive
#   ./test.sh host [unit]   # run host-side units against the real
#                           # source/main.cpp (no device needed)
#

set -u

BASEDIR="$(cd "$(dirname "$0")" && pwd)"
BIN="$BASEDIR/build/aarch64-linux-android23/runnable/dfps"
WORK=/data/local/tmp/dfps_test
DEVICE_SCRIPT="$WORK/dfps_test.sh"
STUBS="$BASEDIR/test/host/stubs"
HOST_WORK="$BASEDIR/build/host_test"
HOST_BIN="$HOST_WORK/dfps_host"
# per-run dir (config, log, pidfiles) so leaked daemons from previous or
# interrupted runs cannot interfere with the current one
HOST_RUN_DIR=""
HOST_CFG=""
HOST_LOG=""

UNITS=(
    t01_start_with_valid_config
    t02_missing_universal_rule_keeps_alive
    t03_missing_offscreen_rule_keeps_alive
    t04_malformed_rule_keeps_alive
    t05_invalid_rule_value_keeps_alive
    t06_valid_config_reloads_new_instance
    t07_recovery_after_bad_config
    t08_bad_initial_config_then_fix
)

HOST_UNITS=(
    h01_start_with_valid_config
    h02_bad_config_keeps_old_instance
    h03_valid_config_reloads_new_instance
    h04_bad_initial_config_then_fix
)

die() { echo "FAIL: $*" >&2; exit 1; }

check_host_prereqs() {
    command -v adb >/dev/null || die "adb not found in PATH"
    [ -f "$BIN" ] || die "dfps binary not found at $BIN (run ./build.sh Debug make first)"
    adb get-state >/dev/null 2>&1 || die "no adb device connected"
    adb shell 'su -c id' 2>/dev/null | grep -q 'uid=0' || die "root (su) not available on device"
}

# Device-side test script. Generated and pushed by cmd_push().
# Runs on Android under: su -c sh <script> <unit>
generate_device_script() {
    cat <<'DEVICE_EOF'
#!/system/bin/sh
# dfps hot-reload keepalive regression units (device side). Do not edit
# directly; this file is generated by test.sh.

WORK=/data/local/tmp/dfps_test
BIN=$WORK/dfps
CFG=$WORK/dfps.txt
LOG=$WORK/dfps.log

# --- configs -------------------------------------------------------------

good_config() {
    cat > $CFG <<'EOF'
# valid config
/touchSlackMs 4000
/useSfBackdoor 0
com.example.app 60 60
- -1 -1
* 60 120
EOF
}

good_config_v2() {
    cat > $CFG <<'EOF'
# valid config, different tunable so a reload is observable
/touchSlackMs 5000
/useSfBackdoor 0
com.example.app 60 60
- -1 -1
* 60 120
EOF
}

config_missing_universal() {
    cat > $CFG <<'EOF'
# invalid: default rule '*' not specified
/useSfBackdoor 0
com.example.app 60 60
- -1 -1
EOF
}

config_missing_offscreen() {
    cat > $CFG <<'EOF'
# invalid: offscreen rule '-' not specified
/useSfBackdoor 0
com.example.app 60 60
* 60 120
EOF
}

config_malformed_rule() {
    cat > $CFG <<'EOF'
# invalid: rule with a missing field
/useSfBackdoor 0
com.broken.app 60
- -1 -1
* 60 120
EOF
}

config_invalid_rule_value() {
    cat > $CFG <<'EOF'
# invalid: backdoor-style values while /useSfBackdoor is 0
/useSfBackdoor 0
- -1 -1
* 2 0
EOF
}

# --- process helpers -----------------------------------------------------

# prints "<pid> <ppid>" for every process running the test binary, so a
# system-installed dfps service (same comm name) is never touched
list_dfps() {
    for p in /proc/[0-9]*; do
        pid=${p#/proc/}
        [ "$(readlink $p/exe 2>/dev/null)" = "$BIN" ] || continue
        ppid=$(awk '{print $4}' $p/stat 2>/dev/null)
        echo "$pid $ppid"
    done
}

daemon_pid() { list_dfps | awk '$2 == 1 {print $1}'; }

app_pid() {
    d=$(daemon_pid)
    [ -n "$d" ] && list_dfps | awk -v d="$d" '$2 == d {print $1}'
}

start_daemon() {
    rm -f $LOG
    # detach stdio: the daemonized process must not hold adb shell's stdout open
    $BIN -o $LOG $CFG >/dev/null 2>&1
    sleep 2 # daemon forks; app instance health-check takes ~1s
}

stop_daemon() {
    for p in $(list_dfps | awk '{print $1}'); do
        kill $p 2>/dev/null
    done
    sleep 1
    for p in $(list_dfps | awk '{print $1}'); do
        kill -9 $p 2>/dev/null
    done
}

# --- assertion helpers ---------------------------------------------------

fail() { echo "  FAIL: $*"; exit 1; }
note() { echo "  $*"; }

assert_app_alive() {
    [ -n "$(app_pid)" ] || fail "app instance is not running"
}

# --- test units ----------------------------------------------------------

t01_start_with_valid_config() {
    good_config
    start_daemon
    [ -n "$(daemon_pid)" ] || fail "daemon is not running"
    assert_app_alive
    note "daemon=$(daemon_pid) app=$(app_pid)"
}

t02_missing_universal_rule_keeps_alive() {
    good_config
    start_daemon
    old=$(app_pid)
    [ -n "$old" ] || fail "no app instance before reload"
    config_missing_universal
    sleep 3
    assert_app_alive
    [ "$(app_pid)" = "$old" ] || fail "bad config killed the running instance (pid $old -> $(app_pid))"
    grep -q "keeps running with the previous config" $LOG || fail "keepalive log line missing"
    note "old instance $old survived a config without the '*' rule"
}

t03_missing_offscreen_rule_keeps_alive() {
    good_config
    start_daemon
    old=$(app_pid)
    [ -n "$old" ] || fail "no app instance before reload"
    config_missing_offscreen
    sleep 3
    assert_app_alive
    [ "$(app_pid)" = "$old" ] || fail "bad config killed the running instance (pid $old -> $(app_pid))"
    grep -q "keeps running with the previous config" $LOG || fail "keepalive log line missing"
    note "old instance $old survived a config without the '-' rule"
}

t04_malformed_rule_keeps_alive() {
    good_config
    start_daemon
    old=$(app_pid)
    [ -n "$old" ] || fail "no app instance before reload"
    config_malformed_rule
    sleep 3
    assert_app_alive
    [ "$(app_pid)" = "$old" ] || fail "bad config killed the running instance (pid $old -> $(app_pid))"
    grep -q "keeps running with the previous config" $LOG || fail "keepalive log line missing"
    note "old instance $old survived a malformed rule"
}

t05_invalid_rule_value_keeps_alive() {
    good_config
    start_daemon
    old=$(app_pid)
    [ -n "$old" ] || fail "no app instance before reload"
    config_invalid_rule_value
    sleep 3
    assert_app_alive
    [ "$(app_pid)" = "$old" ] || fail "bad config killed the running instance (pid $old -> $(app_pid))"
    grep -q "keeps running with the previous config" $LOG || fail "keepalive log line missing"
    note "old instance $old survived invalid refresh rate values"
}

t06_valid_config_reloads_new_instance() {
    good_config
    start_daemon
    old=$(app_pid)
    [ -n "$old" ] || fail "no app instance before reload"
    good_config_v2
    sleep 3
    assert_app_alive
    new=$(app_pid)
    [ "$new" != "$old" ] || fail "valid config did not trigger a reload (still pid $old)"
    grep -q "reloaded with the new config" $LOG || fail "reload log line missing"
    note "instance reloaded: $old -> $new"
}

t07_recovery_after_bad_config() {
    good_config
    start_daemon
    old=$(app_pid)
    [ -n "$old" ] || fail "no app instance before reload"
    config_missing_universal
    sleep 3
    [ "$(app_pid)" = "$old" ] || fail "bad config killed the running instance"
    good_config_v2
    sleep 3
    assert_app_alive
    new=$(app_pid)
    [ "$new" != "$old" ] || fail "service did not recover after fixing the config"
    note "service recovered: $old -> $new"
}

t08_bad_initial_config_then_fix() {
    config_missing_universal
    start_daemon
    [ -n "$(daemon_pid)" ] || fail "daemon is not running"
    [ -z "$(app_pid)" ] || fail "app instance should not run with a bad initial config"
    grep -q "waiting for a valid config" $LOG || fail "waiting log line missing"
    good_config
    sleep 3
    assert_app_alive
    note "service came up after the config was fixed (app=$(app_pid))"
}

# --- runner --------------------------------------------------------------

unit="$1"
if [ -z "$unit" ] || ! type "$unit" >/dev/null 2>&1; then
    echo "usage: sh $0 <unit>" >&2
    exit 2
fi
stop_daemon
trap stop_daemon EXIT
$unit
rc=$?
if [ $rc -eq 0 ]; then
    echo "  PASS: $unit"
fi
exit $rc
DEVICE_EOF
}

cmd_list() {
    printf '%s\n' "${UNITS[@]}"
    printf '%s\n' "${HOST_UNITS[@]}"
}

# --- host-side units -------------------------------------------------------
# These compile the REAL source/main.cpp against lightweight stubs
# (test/host/stubs) so the daemon's reload/keepalive logic is exercised
# directly on macOS/Linux without an Android device.

host_build() {
    local cxx
    cxx="$(command -v clang++ || command -v g++)" || die "no C++ compiler found"
    mkdir -p "$HOST_WORK"
    # compile a copy so quoted includes resolve to the stubs, not source/
    cp "$BASEDIR/source/main.cpp" "$HOST_WORK/main.cpp"
    "$cxx" -std=c++17 -O1 -Wall \
        -Wno-deprecated-declarations -Wno-deprecated-literal-operator \
        -I "$STUBS" -I "$BASEDIR/thirdparty/spdlog" \
        "$HOST_WORK/main.cpp" "$STUBS/dfps.cpp" \
        -o "$HOST_BIN" || die "host build failed"
}

# kill processes recorded by previous runs and remove their run dirs
host_sweep_stale() {
    local d f p
    for d in "$HOST_WORK"/run-*; do
        [ -d "$d" ] || continue
        for f in "$d/dfps.pid" "$d/app.pid"; do
            [ -f "$f" ] || continue
            p=$(cat "$f" 2>/dev/null)
            [ -n "$p" ] && kill "$p" 2>/dev/null
        done
    done
    sleep 1
    for d in "$HOST_WORK"/run-*; do
        [ -d "$d" ] || continue
        for f in "$d/dfps.pid" "$d/app.pid"; do
            [ -f "$f" ] || continue
            p=$(cat "$f" 2>/dev/null)
            [ -n "$p" ] && kill -9 "$p" 2>/dev/null
        done
        rm -rf "$d"
    done
}

# The stubbed processes record their pids into $DFPS_TEST_DIR/*.pid
# (see test/host/stubs), so no ps(1) is needed.
host_pid_from() {
    local f="$HOST_RUN_DIR/$1" p
    [ -f "$f" ] || return 0
    p=$(cat "$f" 2>/dev/null)
    [ -n "$p" ] && kill -0 "$p" 2>/dev/null && echo "$p"
}

host_daemon_pid() { host_pid_from dfps.pid; }

host_app_pid() { host_pid_from app.pid; }

host_good_config() {
    cat >"$HOST_CFG" <<'EOF'
# valid config
/useSfBackdoor 0
com.example.app 60 60
- -1 -1
* 60 120
EOF
}

host_good_config_v2() {
    cat >"$HOST_CFG" <<'EOF'
# valid config, edited so a reload is observable
/useSfBackdoor 0
com.example.app 60 60
com.example.other 30 60
- -1 -1
* 60 120
EOF
}

host_bad_config() {
    cat >"$HOST_CFG" <<'EOF'
# invalid: default rule '*' not specified
/useSfBackdoor 0
com.example.app 60 60
- -1 -1
EOF
}

host_start() {
    rm -f "$HOST_LOG"
    rm -f "$HOST_RUN_DIR/dfps.pid" "$HOST_RUN_DIR/app.pid"
    # detach stdio: the daemonized process must not hold our stdout open
    "$HOST_BIN" -o "$HOST_LOG" "$HOST_CFG" >/dev/null 2>&1
    sleep 2 # daemon forks; app instance health-check takes ~1s
}

host_stop() {
    local p
    for p in $(cat "$HOST_RUN_DIR/dfps.pid" "$HOST_RUN_DIR/app.pid" 2>/dev/null); do
        kill "$p" 2>/dev/null
    done
    sleep 1
    for p in $(cat "$HOST_RUN_DIR/dfps.pid" "$HOST_RUN_DIR/app.pid" 2>/dev/null); do
        kill -9 "$p" 2>/dev/null
    done
    rm -f "$HOST_RUN_DIR/dfps.pid" "$HOST_RUN_DIR/app.pid"
}

h01_start_with_valid_config() {
    host_good_config
    host_start
    [ -n "$(host_daemon_pid)" ] || { echo "  FAIL: daemon is not running"; return 1; }
    [ -n "$(host_app_pid)" ] || { echo "  FAIL: app instance is not running"; return 1; }
    echo "  daemon=$(host_daemon_pid) app=$(host_app_pid)"
}

h02_bad_config_keeps_old_instance() {
    host_good_config
    host_start
    local old
    old=$(host_app_pid)
    [ -n "$old" ] || { echo "  FAIL: no app instance before reload"; return 1; }
    host_bad_config
    sleep 3
    [ "$(host_app_pid)" = "$old" ] || {
        echo "  FAIL: bad config killed the running instance (pid $old -> $(host_app_pid))"
        return 1
    }
    grep -q "keeps running with the previous config" "$HOST_LOG" || {
        echo "  FAIL: keepalive log line missing"
        return 1
    }
    echo "  old instance $old survived a bad config"
}

h03_valid_config_reloads_new_instance() {
    host_good_config
    host_start
    local old new
    old=$(host_app_pid)
    [ -n "$old" ] || { echo "  FAIL: no app instance before reload"; return 1; }
    host_good_config_v2
    sleep 3
    new=$(host_app_pid)
    [ -n "$new" ] || { echo "  FAIL: app instance is not running after reload"; return 1; }
    [ "$new" != "$old" ] || { echo "  FAIL: valid config did not trigger a reload (still pid $old)"; return 1; }
    grep -q "reloaded with the new config" "$HOST_LOG" || {
        echo "  FAIL: reload log line missing"
        return 1
    }
    echo "  instance reloaded: $old -> $new"
}

h04_bad_initial_config_then_fix() {
    host_bad_config
    host_start
    [ -n "$(host_daemon_pid)" ] || { echo "  FAIL: daemon is not running"; return 1; }
    [ -z "$(host_app_pid)" ] || { echo "  FAIL: app instance should not run with a bad initial config"; return 1; }
    grep -q "waiting for a valid config" "$HOST_LOG" || { echo "  FAIL: waiting log line missing"; return 1; }
    host_good_config
    sleep 3
    [ -n "$(host_app_pid)" ] || { echo "  FAIL: service did not come up after the config was fixed"; return 1; }
    echo "  service came up after the config was fixed (app=$(host_app_pid))"
}

run_host_unit() {
    local unit="$1"
    echo ">>> $unit"
    host_stop
    "$unit"
    local rc=$?
    cp "$HOST_LOG" "$HOST_RUN_DIR/$unit.log" 2>/dev/null
    host_stop
    if [ $rc -eq 0 ]; then
        echo "  PASS: $unit"
    else
        echo ">>> $unit FAILED"
    fi
    return $rc
}

cmd_host() {
    local targets=("$@")
    if [ "${#targets[@]}" -eq 0 ]; then
        targets=("${HOST_UNITS[@]}")
    fi
    host_sweep_stale
    HOST_RUN_DIR="$HOST_WORK/run-$$"
    mkdir -p "$HOST_RUN_DIR"
    HOST_CFG="$HOST_RUN_DIR/dfps.txt"
    HOST_LOG="$HOST_RUN_DIR/dfps.log"
    host_build
    export DFPS_TEST_DIR="$HOST_RUN_DIR"
    trap host_stop EXIT
    local failed=()
    local u
    for u in "${targets[@]}"; do
        run_host_unit "$u" || failed+=("$u")
    done
    echo
    if [ "${#failed[@]}" -eq 0 ]; then
        echo "ALL HOST UNITS PASSED (${#targets[@]} unit(s))"
    else
        echo "FAILED UNITS: ${failed[*]}"
        return 1
    fi
}

cmd_push() {
    check_host_prereqs
    mkdir -p "$BASEDIR/build"
    adb shell 'su -c "mkdir -p '$WORK'"' || die "cannot create $WORK"
    adb push "$BIN" "$WORK/dfps" >/dev/null || die "cannot push dfps binary"
    generate_device_script >"$BASEDIR/build/dfps_test_device.sh"
    adb push "$BASEDIR/build/dfps_test_device.sh" "$DEVICE_SCRIPT" >/dev/null || die "cannot push device script"
    adb shell 'su -c "chmod 755 '$WORK/dfps' '$DEVICE_SCRIPT'"'
    echo "pushed dfps + device script to $WORK"
}

run_unit() {
    local unit="$1"
    echo ">>> $unit"
    adb shell "su -c 'sh $DEVICE_SCRIPT $unit'"
    local rc=$?
    if [ $rc -ne 0 ]; then
        echo ">>> $unit FAILED (rc=$rc)"
        return $rc
    fi
    return 0
}

main() {
    local targets=("$@")
    if [ "${#targets[@]}" -eq 0 ] || [ "${targets[0]}" = "all" ]; then
        targets=("${UNITS[@]}")
    fi
    case "${targets[0]}" in
    list)
        cmd_list
        return 0
        ;;
    host)
        cmd_host "${targets[@]:1}"
        return $?
        ;;
    push)
        cmd_push
        return 0
        ;;
    esac

    check_host_prereqs
    cmd_push

    local failed=()
    for u in "${targets[@]}"; do
        run_unit "$u" || failed+=("$u")
    done

    echo
    if [ "${#failed[@]}" -eq 0 ]; then
        echo "ALL PASSED (${#targets[@]} unit(s))"
    else
        echo "FAILED UNITS: ${failed[*]}"
        return 1
    fi
}

main "$@"
